// Code generated by ent, DO NOT EDIT.

package ent

import (
	"_models/ent/message"
	"_models/ent/predicate"
	"_models/ent/queue"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// MessageUpdate is the builder for updating Message entities.
type MessageUpdate struct {
	config
	hooks    []Hook
	mutation *MessageMutation
}

// Where appends a list predicates to the MessageUpdate builder.
func (mu *MessageUpdate) Where(ps ...predicate.Message) *MessageUpdate {
	mu.mutation.Where(ps...)
	return mu
}

// SetBody sets the "body" field.
func (mu *MessageUpdate) SetBody(s string) *MessageUpdate {
	mu.mutation.SetBody(s)
	return mu
}

// SetContentType sets the "content_type" field.
func (mu *MessageUpdate) SetContentType(s string) *MessageUpdate {
	mu.mutation.SetContentType(s)
	return mu
}

// SetStatus sets the "status" field.
func (mu *MessageUpdate) SetStatus(s string) *MessageUpdate {
	mu.mutation.SetStatus(s)
	return mu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (mu *MessageUpdate) SetNillableStatus(s *string) *MessageUpdate {
	if s != nil {
		mu.SetStatus(*s)
	}
	return mu
}

// SetMaxRetries sets the "max_retries" field.
func (mu *MessageUpdate) SetMaxRetries(u uint) *MessageUpdate {
	mu.mutation.ResetMaxRetries()
	mu.mutation.SetMaxRetries(u)
	return mu
}

// SetNillableMaxRetries sets the "max_retries" field if the given value is not nil.
func (mu *MessageUpdate) SetNillableMaxRetries(u *uint) *MessageUpdate {
	if u != nil {
		mu.SetMaxRetries(*u)
	}
	return mu
}

// AddMaxRetries adds u to the "max_retries" field.
func (mu *MessageUpdate) AddMaxRetries(u int) *MessageUpdate {
	mu.mutation.AddMaxRetries(u)
	return mu
}

// SetAvailableFrom sets the "available_from" field.
func (mu *MessageUpdate) SetAvailableFrom(t time.Time) *MessageUpdate {
	mu.mutation.SetAvailableFrom(t)
	return mu
}

// SetNillableAvailableFrom sets the "available_from" field if the given value is not nil.
func (mu *MessageUpdate) SetNillableAvailableFrom(t *time.Time) *MessageUpdate {
	if t != nil {
		mu.SetAvailableFrom(*t)
	}
	return mu
}

// SetCreatedAt sets the "created_at" field.
func (mu *MessageUpdate) SetCreatedAt(t time.Time) *MessageUpdate {
	mu.mutation.SetCreatedAt(t)
	return mu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (mu *MessageUpdate) SetNillableCreatedAt(t *time.Time) *MessageUpdate {
	if t != nil {
		mu.SetCreatedAt(*t)
	}
	return mu
}

// AddQueueIDs adds the "queue" edge to the Queue entity by IDs.
func (mu *MessageUpdate) AddQueueIDs(ids ...uuid.UUID) *MessageUpdate {
	mu.mutation.AddQueueIDs(ids...)
	return mu
}

// AddQueue adds the "queue" edges to the Queue entity.
func (mu *MessageUpdate) AddQueue(q ...*Queue) *MessageUpdate {
	ids := make([]uuid.UUID, len(q))
	for i := range q {
		ids[i] = q[i].ID
	}
	return mu.AddQueueIDs(ids...)
}

// Mutation returns the MessageMutation object of the builder.
func (mu *MessageUpdate) Mutation() *MessageMutation {
	return mu.mutation
}

// ClearQueue clears all "queue" edges to the Queue entity.
func (mu *MessageUpdate) ClearQueue() *MessageUpdate {
	mu.mutation.ClearQueue()
	return mu
}

// RemoveQueueIDs removes the "queue" edge to Queue entities by IDs.
func (mu *MessageUpdate) RemoveQueueIDs(ids ...uuid.UUID) *MessageUpdate {
	mu.mutation.RemoveQueueIDs(ids...)
	return mu
}

// RemoveQueue removes "queue" edges to Queue entities.
func (mu *MessageUpdate) RemoveQueue(q ...*Queue) *MessageUpdate {
	ids := make([]uuid.UUID, len(q))
	for i := range q {
		ids[i] = q[i].ID
	}
	return mu.RemoveQueueIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (mu *MessageUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(mu.hooks) == 0 {
		affected, err = mu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*MessageMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			mu.mutation = mutation
			affected, err = mu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(mu.hooks) - 1; i >= 0; i-- {
			if mu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = mu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, mu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (mu *MessageUpdate) SaveX(ctx context.Context) int {
	affected, err := mu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (mu *MessageUpdate) Exec(ctx context.Context) error {
	_, err := mu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mu *MessageUpdate) ExecX(ctx context.Context) {
	if err := mu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (mu *MessageUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   message.Table,
			Columns: message.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: message.FieldID,
			},
		},
	}
	if ps := mu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mu.mutation.Body(); ok {
		_spec.SetField(message.FieldBody, field.TypeString, value)
	}
	if value, ok := mu.mutation.ContentType(); ok {
		_spec.SetField(message.FieldContentType, field.TypeString, value)
	}
	if value, ok := mu.mutation.Status(); ok {
		_spec.SetField(message.FieldStatus, field.TypeString, value)
	}
	if value, ok := mu.mutation.MaxRetries(); ok {
		_spec.SetField(message.FieldMaxRetries, field.TypeUint, value)
	}
	if value, ok := mu.mutation.AddedMaxRetries(); ok {
		_spec.AddField(message.FieldMaxRetries, field.TypeUint, value)
	}
	if value, ok := mu.mutation.AvailableFrom(); ok {
		_spec.SetField(message.FieldAvailableFrom, field.TypeTime, value)
	}
	if value, ok := mu.mutation.CreatedAt(); ok {
		_spec.SetField(message.FieldCreatedAt, field.TypeTime, value)
	}
	if mu.mutation.QueueCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   message.QueueTable,
			Columns: message.QueuePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: queue.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mu.mutation.RemovedQueueIDs(); len(nodes) > 0 && !mu.mutation.QueueCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   message.QueueTable,
			Columns: message.QueuePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: queue.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mu.mutation.QueueIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   message.QueueTable,
			Columns: message.QueuePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: queue.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, mu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{message.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// MessageUpdateOne is the builder for updating a single Message entity.
type MessageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MessageMutation
}

// SetBody sets the "body" field.
func (muo *MessageUpdateOne) SetBody(s string) *MessageUpdateOne {
	muo.mutation.SetBody(s)
	return muo
}

// SetContentType sets the "content_type" field.
func (muo *MessageUpdateOne) SetContentType(s string) *MessageUpdateOne {
	muo.mutation.SetContentType(s)
	return muo
}

// SetStatus sets the "status" field.
func (muo *MessageUpdateOne) SetStatus(s string) *MessageUpdateOne {
	muo.mutation.SetStatus(s)
	return muo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (muo *MessageUpdateOne) SetNillableStatus(s *string) *MessageUpdateOne {
	if s != nil {
		muo.SetStatus(*s)
	}
	return muo
}

// SetMaxRetries sets the "max_retries" field.
func (muo *MessageUpdateOne) SetMaxRetries(u uint) *MessageUpdateOne {
	muo.mutation.ResetMaxRetries()
	muo.mutation.SetMaxRetries(u)
	return muo
}

// SetNillableMaxRetries sets the "max_retries" field if the given value is not nil.
func (muo *MessageUpdateOne) SetNillableMaxRetries(u *uint) *MessageUpdateOne {
	if u != nil {
		muo.SetMaxRetries(*u)
	}
	return muo
}

// AddMaxRetries adds u to the "max_retries" field.
func (muo *MessageUpdateOne) AddMaxRetries(u int) *MessageUpdateOne {
	muo.mutation.AddMaxRetries(u)
	return muo
}

// SetAvailableFrom sets the "available_from" field.
func (muo *MessageUpdateOne) SetAvailableFrom(t time.Time) *MessageUpdateOne {
	muo.mutation.SetAvailableFrom(t)
	return muo
}

// SetNillableAvailableFrom sets the "available_from" field if the given value is not nil.
func (muo *MessageUpdateOne) SetNillableAvailableFrom(t *time.Time) *MessageUpdateOne {
	if t != nil {
		muo.SetAvailableFrom(*t)
	}
	return muo
}

// SetCreatedAt sets the "created_at" field.
func (muo *MessageUpdateOne) SetCreatedAt(t time.Time) *MessageUpdateOne {
	muo.mutation.SetCreatedAt(t)
	return muo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (muo *MessageUpdateOne) SetNillableCreatedAt(t *time.Time) *MessageUpdateOne {
	if t != nil {
		muo.SetCreatedAt(*t)
	}
	return muo
}

// AddQueueIDs adds the "queue" edge to the Queue entity by IDs.
func (muo *MessageUpdateOne) AddQueueIDs(ids ...uuid.UUID) *MessageUpdateOne {
	muo.mutation.AddQueueIDs(ids...)
	return muo
}

// AddQueue adds the "queue" edges to the Queue entity.
func (muo *MessageUpdateOne) AddQueue(q ...*Queue) *MessageUpdateOne {
	ids := make([]uuid.UUID, len(q))
	for i := range q {
		ids[i] = q[i].ID
	}
	return muo.AddQueueIDs(ids...)
}

// Mutation returns the MessageMutation object of the builder.
func (muo *MessageUpdateOne) Mutation() *MessageMutation {
	return muo.mutation
}

// ClearQueue clears all "queue" edges to the Queue entity.
func (muo *MessageUpdateOne) ClearQueue() *MessageUpdateOne {
	muo.mutation.ClearQueue()
	return muo
}

// RemoveQueueIDs removes the "queue" edge to Queue entities by IDs.
func (muo *MessageUpdateOne) RemoveQueueIDs(ids ...uuid.UUID) *MessageUpdateOne {
	muo.mutation.RemoveQueueIDs(ids...)
	return muo
}

// RemoveQueue removes "queue" edges to Queue entities.
func (muo *MessageUpdateOne) RemoveQueue(q ...*Queue) *MessageUpdateOne {
	ids := make([]uuid.UUID, len(q))
	for i := range q {
		ids[i] = q[i].ID
	}
	return muo.RemoveQueueIDs(ids...)
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (muo *MessageUpdateOne) Select(field string, fields ...string) *MessageUpdateOne {
	muo.fields = append([]string{field}, fields...)
	return muo
}

// Save executes the query and returns the updated Message entity.
func (muo *MessageUpdateOne) Save(ctx context.Context) (*Message, error) {
	var (
		err  error
		node *Message
	)
	if len(muo.hooks) == 0 {
		node, err = muo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*MessageMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			muo.mutation = mutation
			node, err = muo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(muo.hooks) - 1; i >= 0; i-- {
			if muo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = muo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, muo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Message)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from MessageMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (muo *MessageUpdateOne) SaveX(ctx context.Context) *Message {
	node, err := muo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (muo *MessageUpdateOne) Exec(ctx context.Context) error {
	_, err := muo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (muo *MessageUpdateOne) ExecX(ctx context.Context) {
	if err := muo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (muo *MessageUpdateOne) sqlSave(ctx context.Context) (_node *Message, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   message.Table,
			Columns: message.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: message.FieldID,
			},
		},
	}
	id, ok := muo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Message.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := muo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, message.FieldID)
		for _, f := range fields {
			if !message.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != message.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := muo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := muo.mutation.Body(); ok {
		_spec.SetField(message.FieldBody, field.TypeString, value)
	}
	if value, ok := muo.mutation.ContentType(); ok {
		_spec.SetField(message.FieldContentType, field.TypeString, value)
	}
	if value, ok := muo.mutation.Status(); ok {
		_spec.SetField(message.FieldStatus, field.TypeString, value)
	}
	if value, ok := muo.mutation.MaxRetries(); ok {
		_spec.SetField(message.FieldMaxRetries, field.TypeUint, value)
	}
	if value, ok := muo.mutation.AddedMaxRetries(); ok {
		_spec.AddField(message.FieldMaxRetries, field.TypeUint, value)
	}
	if value, ok := muo.mutation.AvailableFrom(); ok {
		_spec.SetField(message.FieldAvailableFrom, field.TypeTime, value)
	}
	if value, ok := muo.mutation.CreatedAt(); ok {
		_spec.SetField(message.FieldCreatedAt, field.TypeTime, value)
	}
	if muo.mutation.QueueCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   message.QueueTable,
			Columns: message.QueuePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: queue.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := muo.mutation.RemovedQueueIDs(); len(nodes) > 0 && !muo.mutation.QueueCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   message.QueueTable,
			Columns: message.QueuePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: queue.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := muo.mutation.QueueIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   message.QueueTable,
			Columns: message.QueuePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: queue.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Message{config: muo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, muo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{message.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
