// Code generated by ent, DO NOT EDIT.

package ent

import (
	"_models/ent/predicate"
	"_models/ent/queuemessage"
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// QueueMessageDelete is the builder for deleting a QueueMessage entity.
type QueueMessageDelete struct {
	config
	hooks    []Hook
	mutation *QueueMessageMutation
}

// Where appends a list predicates to the QueueMessageDelete builder.
func (qmd *QueueMessageDelete) Where(ps ...predicate.QueueMessage) *QueueMessageDelete {
	qmd.mutation.Where(ps...)
	return qmd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (qmd *QueueMessageDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(qmd.hooks) == 0 {
		affected, err = qmd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*QueueMessageMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			qmd.mutation = mutation
			affected, err = qmd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(qmd.hooks) - 1; i >= 0; i-- {
			if qmd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = qmd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, qmd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (qmd *QueueMessageDelete) ExecX(ctx context.Context) int {
	n, err := qmd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (qmd *QueueMessageDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: queuemessage.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: queuemessage.FieldID,
			},
		},
	}
	if ps := qmd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, qmd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// QueueMessageDeleteOne is the builder for deleting a single QueueMessage entity.
type QueueMessageDeleteOne struct {
	qmd *QueueMessageDelete
}

// Exec executes the deletion query.
func (qmdo *QueueMessageDeleteOne) Exec(ctx context.Context) error {
	n, err := qmdo.qmd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{queuemessage.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (qmdo *QueueMessageDeleteOne) ExecX(ctx context.Context) {
	qmdo.qmd.ExecX(ctx)
}
